<?php
/**
 * Permissions & capabilities manager.
 *
 * @package WooTotalMenu
 */

namespace WooTotalMenu\Core;

if ( ! defined( 'ABSPATH' ) ) {
        exit;
}

/**
 * Class Permissions
 *
 * Registers custom capabilities and provides helpers for permission checks.
 *
 * The CPT `wtm_menu` uses `capability_type => array('wtm_menu', 'wtm_menus')`
 * which generates the following primitive caps:
 *   - edit_wtm_menu, edit_wtm_menus
 *   - edit_others_wtm_menus
 *   - publish_wtm_menus
 *   - read_private_wtm_menus
 *   - delete_wtm_menu, delete_wtm_menus
 *   - delete_others_wtm_menus
 *   - delete_private_wtm_menus
 *   - delete_published_wtm_menus
 *   - edit_private_wtm_menus
 *   - edit_published_wtm_menus
 *   - create_wtm_menus
 *
 * We GRANT all these primitive caps to roles that have `manage_options`
 * (typically administrators). We also keep the high-level caps
 * `wtm_manage_menus`, `wtm_manage_templates`, `wtm_view_analytics`,
 * `wtm_manage_settings` for use in our own admin pages and REST endpoints.
 */
class Permissions {

        /**
         * High-level capabilities used by our admin pages and REST endpoints.
         *
         * These are the "user-facing" caps. The CPT primitive caps
         * (edit_wtm_menu, etc.) are derived from `capability_type` and
         * granted automatically.
         *
         * @var array<string,string>
         */
        const HIGH_LEVEL_CAPS = array(
                'wtm_manage_menus'      => 'manage_options',
                'wtm_manage_templates'  => 'manage_options',
                'wtm_view_analytics'    => 'manage_options',
                'wtm_manage_settings'   => 'manage_options',
        );

        /**
         * CPT primitive caps to grant to roles with `manage_options`.
         *
         * Generated by `capability_type => array('wtm_menu', 'wtm_menus')`.
         *
         * @var array<string>
         */
        const CPT_PRIMITIVE_CAPS = array(
                'edit_wtm_menu',
                'edit_wtm_menus',
                'edit_others_wtm_menus',
                'publish_wtm_menus',
                'read_private_wtm_menus',
                'delete_wtm_menu',
                'delete_wtm_menus',
                'delete_others_wtm_menus',
                'delete_private_wtm_menus',
                'delete_published_wtm_menus',
                'edit_private_wtm_menus',
                'edit_published_wtm_menus',
                'create_wtm_menus',
        );

        /**
         * Backwards-compatible alias.
         *
         * @var array<string,string>
         */
        const CAPABILITIES = self::HIGH_LEVEL_CAPS;

        /**
         * Add capabilities to roles on activation.
         *
         * @return void
         */
        public function register_caps() {
                $roles = wp_roles()->roles;
                foreach ( $roles as $role_name => $role_info ) {
                        $role = get_role( $role_name );
                        if ( ! $role ) {
                                continue;
                        }
                        // Only grant to roles that already have manage_options.
                        $has_manage = ! empty( $role_info['capabilities']['manage_options'] );

                        // High-level caps.
                        foreach ( self::HIGH_LEVEL_CAPS as $cap => $from ) {
                                if ( $has_manage || 'administrator' === $role_name ) {
                                        $role->add_cap( $cap );
                                }
                        }

                        // CPT primitive caps.
                        if ( $has_manage || 'administrator' === $role_name ) {
                                foreach ( self::CPT_PRIMITIVE_CAPS as $cap ) {
                                        $role->add_cap( $cap );
                                }
                        }
                }
        }

        /**
         * Remove capabilities from roles on uninstall.
         *
         * @return void
         */
        public function remove_caps() {
                $all_caps = array_merge(
                        array_keys( self::HIGH_LEVEL_CAPS ),
                        self::CPT_PRIMITIVE_CAPS
                );
                foreach ( array_keys( wp_roles()->roles ) as $role_name ) {
                        $role = get_role( $role_name );
                        if ( $role ) {
                                foreach ( $all_caps as $cap ) {
                                        $role->remove_cap( $cap );
                                }
                        }
                }
        }

        /**
         * Check whether the current user has a capability.
         *
         * @param string $cap Capability slug.
         * @return bool
         */
        public function user_can( $cap ) {
                return current_user_can( $cap );
        }

        /**
         * Ensure the current user can manage menus, die otherwise.
         *
         * @return void
         */
        public function assert_can_manage_menus() {
                if ( ! $this->user_can( 'wtm_manage_menus' ) ) {
                        wp_die( esc_html__( 'You do not have permission to manage Woo Total Menu.', 'woo-total-menu' ), 403 );
                }
        }
}
